Repository FRONT-END-BOOTCAMP-PLUS-4/eat-the-weather, pull requests merged in 2025-04, with the labels that each got.

#3 [Design] 기본 레이아웃 작업
  app/auth/login/page.tsx
  app/auth/sign-up/page.tsx
  app/components/NavBar.tsx
  app/layout.tsx
  app/page.tsx
  package.json
Labels: 🎨 UI

#12 [FEATURE] Domain/entities 작성 및 supabase client객체 생성
  domain/entities/Comment.ts
  domain/entities/Like.ts
  domain/entities/Post.ts
  domain/entities/PostTag.ts
  domain/entities/Region.ts
  domain/entities/Tag.ts
  domain/entities/User.ts
  domain/entities/UserRegionFavorite.ts
  infra/repositories/supabase/Sbclient.ts
  package.json
Labels: ✨ Feature

#14 [FEATURE] onboarding 퍼블리싱
  app/onboarding/components/ChoiceButton.tsx
  app/onboarding/page.tsx
  app/onboarding/step1/page.tsx
  app/onboarding/step2/page.tsx
  app/onboarding/step3/page.tsx
  app/page.tsx
Labels: ✨ Feature

#22 [FEATURE] domain/entities 수정
  domain/entities/Like.ts
  domain/entities/Post.ts
  domain/entities/User.ts
  domain/entities/UserRegionFavorite.ts
Labels: ✨ Feature

#23 [DESIGN] 게시판 페이지 UI 작업
  app/components/PostItem.tsx
  app/components/SensitivityBadge.tsx
  app/components/TagFilter.tsx
  app/posts/page.tsx
  components/ui/badge.tsx
  components/ui/checkbox.tsx
  components/ui/scroll-area.tsx
  components/ui/select.tsx
  components/ui/separator.tsx
  package.json
Labels: 🎨 UI

#28 [DESIGN] post detail 페이지 UI 작업
  app/components/CommentItems.tsx
  app/components/PostItem.tsx
  app/components/SensitivityBadge.tsx
  app/posts/detail/page.tsx
  app/posts/page.tsx
Labels: 🎨 UI

#29 [DESIGN] 게시물 작성 페이지 UI 작업
  app/components/PostItem.tsx
  app/components/PostUserBox.tsx
  app/posts/new/page.tsx
  components/ui/textarea.tsx
Labels: 🎨 UI

#32 [FEATURE] 게시판 수정 페이지 UI 작업
  app/components/PostForm.tsx
  app/posts/edit/page.tsx
  app/posts/new/page.tsx
Labels: 🎨 UI

#31 [FEATURE] 로그인/회원가입 쿠키 -> 토큰 사용으로 수정 작업
  app/api/auth/login/route.ts
  app/api/auth/logout/route.ts
  app/api/auth/refresh/route.ts
  app/api/auth/sign-up/route.ts
  app/auth/login/page.tsx
  application/usecases/auth/EmailLoginUsecase.ts
  lib/axios.ts
  package.json
  utils/AuthToken.ts
  utils/cookie.ts
Labels: ✨ Feature

#36 [FEATURE] 지역 테이블 API 작업
  app/api/region/[name]/route.ts
  app/api/region/route.ts
  application/usecases/region/GetAllRegionsUsecase.ts
  application/usecases/region/GetCoordsUsecase.ts
  application/usecases/region/GetRegionByCoordsUsecase.ts
  application/usecases/region/dto/KakaoLocationDto.ts
  domain/entities/Region.ts
  domain/repositories/RegionRepository.ts
  infra/repositories/kakao/KkRegionRepository.ts
  infra/repositories/supabase/SbRegionRepository.ts
  utils/geo.ts
Labels: 📬 API

#37 [FEATURE] 지역 즐겨찾기 테이블 API 작업
  app/api/region-favorite/[user_id]/route.ts
  app/api/region-favorite/route.ts
  application/usecases/regionFavorite/CreateRegionFavoriteUsecase.ts
  application/usecases/regionFavorite/DeleteRegionFavoriteUsecase.ts
  application/usecases/regionFavorite/GetByUserIdRegionUsecase.ts
  application/usecases/regionFavorite/UpdateRegionFavoriteUsecase.ts
  application/usecases/regionFavorite/dto/RegionFavoriteDto.ts
  domain/repositories/RegionFavoriteRepository.ts
  infra/repositories/supabase/SbRegionFavoriteRepository.ts
Labels: 📬 API

#38 [DESIGN] 날씨 페이지 퍼블리싱
  app/api/weather/route.ts
  app/weather/Hourly.tsx
  app/weather/Weekly.tsx
  app/weather/page.tsx
  components/ui/card.tsx
  components/ui/chart.tsx
  components/ui/skeleton.tsx
  components/ui/tabs.tsx
  package.json
Labels: 🎨 UI

#39 [FEATURE] 로그인 , 인증 관련 로직 작업
  app/api/auth/sign-up/route.ts
  app/api/region/[name]/route.ts
  app/api/user/[email]/route.ts
  app/auth/login/page.tsx
  app/auth/sign-up/page.tsx
  app/components/RegionSearchComboBox.tsx
  app/mypage/page.tsx
  app/onboarding/page.tsx
  app/onboarding/step1/page.tsx
  app/onboarding/step2/page.tsx
  app/onboarding/step3/page.tsx
  app/onboarding/step4/page.tsx
  application/usecases/user/GetUserInfoUsecase.ts
  infra/repositories/supabase/SbUserRepository.ts
  lib/axios.ts
  package.json
  store/userStore.ts
Labels: ✨ Feature, 📬 API

#42 [FIX] 유저 id로 지역 정보 받아오는 api view 생성 및 반영
  application/usecases/regionFavorite/GetByUserIdRegionUsecase.ts
  application/usecases/regionFavorite/dto/RegionFavoriteDto.ts
  domain/repositories/RegionFavoriteRepository.ts
  infra/repositories/supabase/SbRegionFavoriteRepository.ts
Labels: 🐞 Bug

#43 [FEATURE] 게시글 생성
  app/api/posts/route.ts
  app/components/PostForm.tsx
  app/posts/new/page.tsx
  app/posts/page.tsx
  application/usecases/post/CreatePostUsecase.ts
  application/usecases/post/dto/PostCreateDto.ts
  application/usecases/post/dto/PostDto.ts.ts
  domain/repositories/PostRepository.ts
  infra/repositories/supabase/SbPostRepository.ts
Labels: ✨ Feature

#46 [FEATURE] 게시판 무한스크롤
  app/posts/page.tsx
  application/usecases/post/GetAllPostsUsecase.ts
  infra/repositories/supabase/SbPostRepository.ts
Labels: ✨ Feature

#47 [FEATURE] 날씨 API 연동
  app/components/ComBoBox.tsx
  app/page.tsx
  app/weather/Hourly.tsx
  app/weather/Weekly.tsx
  app/weather/page.tsx
  lib/hooks/useAutoLocation.ts
  lib/hooks/useCheckAuth.ts
  lib/hooks/useCoords.ts
  lib/hooks/useWeather.ts
  lib/types/weather.ts
  store/useFavoriteRegion.ts
  store/userStore.ts
Labels: 📬 API

#50 [FEATURE] 마이페이지 UI , API 연동 작업
  app/api/region-favorite/route.ts
  app/auth/kakao/callback/page.tsx
  app/auth/login/page.tsx
  app/components/PostItem.tsx
  app/mypage/likes/page.tsx
  app/mypage/page.tsx
  app/mypage/posts/page.tsx
  app/mypage/regions/page.tsx
  app/onboarding/page.tsx
  app/onboarding/step1/page.tsx
  app/onboarding/step2/page.tsx
  app/onboarding/step3/page.tsx
  app/onboarding/step4/page.tsx
  app/posts/page.tsx
  application/usecases/regionFavorite/UpdateRegionFavoriteUsecase.ts
  components/ui/table.tsx
  lib/axios.ts
  store/onboardingStore.ts
  store/userStore.ts
Labels: ✨ Feature, 🎨 UI, 📬 API

#52 [FEATURE] 좋아요 기능 및 게시글 지역 필터링 추가
  app/api/posts/[post-id]/like/route.ts
  app/components/LikeButton.tsx
  app/components/LikeHeart.tsx
  app/components/PostItem.tsx
  app/posts/new/page.tsx
  app/posts/page.tsx
  application/usecases/like/AddLikeUsecase.ts
  application/usecases/like/RemoveLikeUsecase.ts
  domain/entities/PostView.ts
  domain/repositories/LikeRepository.ts
  infra/repositories/supabase/SbLikeRepository.ts
  infra/repositories/supabase/SbPostRepository.ts
Labels: ✨ Feature, 📬 API

#53 [FEATURE] 멤버 정보 관련 작업
  app/api/user/update/route.ts
  app/auth/login/page.tsx
  app/auth/sign-up/page.tsx
  app/components/NavBar.tsx
  app/layout.tsx
  app/member/page.tsx
  app/member/regions/page.tsx
  app/page.tsx
  infra/repositories/supabase/SbRegionFavoriteRepository.ts
Labels: ✨ Feature, 🎨 UI

#55 [FEATURE] 게시물 상세 페이지 좋아요 적용 및 수정
  app/api/posts/[post-id]/route.ts
  app/posts/[post-id]/page.tsx
  application/usecases/post/GetPostByIdUsecase .ts
  application/usecases/post/dto/GetPostByIdDto.ts
  domain/entities/Post.ts
  domain/repositories/PostRepository.ts
  infra/repositories/supabase/SbPostRepository.ts
Labels: ✨ Feature, 📬 API

#56 [FEATURE] 댓글 API 연동
  app/api/comment/[comment_id]/route.ts
  app/api/posts/[post-id]/comments/route.ts
  app/components/CommentItems.tsx
  app/posts/[post-id]/page.tsx
  application/usecases/comment/GetCommentUsecase.ts
  application/usecases/comment/dto/GetCommentDto.ts
  domain/entities/Comment.ts
  infra/repositories/supabase/SbCommentRepository.ts
Labels: 📬 API

#58 [FEATURE] 홈화면 새로고침시 날씨 정보 API 연결
  app/components/ComBoBox.tsx
  app/page.tsx
  domain/entities/Region.ts
Labels: 🐞 Bug, 📬 API

#59 [FEATURE] 게시판 삭제 API
  app/api/posts/[post-id]/route.ts
  application/usecases/post/DeletePostUsecase.ts
Labels: ✨ Feature

#60 [FEATURE] 이미지 업로드 로직 추가 및 UI 디테일 수정
  app/auth/kakao/callback/page.tsx
  app/components/BackButton.tsx
  app/components/LoadingBar.tsx
  app/components/PostForm.tsx
  app/components/PostHeader.tsx
  app/components/PostItem.tsx
  app/components/PostUserBox.tsx
  app/globals.css
  app/member/likes/page.tsx
  app/member/page.tsx
  app/member/posts/page.tsx
  app/member/regions/page.tsx
  app/onboarding/page.tsx
  app/posts/[post-id]/page.tsx
  app/posts/new/page.tsx
  app/posts/page.tsx
  app/weather/page.tsx
  public/images/cloud.png
  public/images/snow.png
  public/images/sun.png
  public/images/teru.png
Labels: ✨ Feature, 🎨 UI, 🐞 Bug

#61 [FEATURE] 게시물 삭제 처리, 좋아요 동기화, 게시판 로그인 처리
  app/api/posts/[post-id]/route.ts
  app/api/posts/liked/route.ts
  app/api/posts/member/route.ts
  app/components/LikeButton.tsx
  app/components/PostForm.tsx
  app/components/PostItem.tsx
  app/member/likes/page.tsx
  app/member/posts/page.tsx
  app/posts/[post-id]/edit/page.tsx
  app/posts/[post-id]/page.tsx
  app/posts/page.tsx
  application/usecases/post/GetLikedPostsUsecase.ts
  application/usecases/post/GetMyPostsUsecase.ts
  application/usecases/post/UpdatePostUsecase.ts
  application/usecases/post/dto/GetLikedPostsDto.ts
  application/usecases/post/dto/GetMyPostsDto.ts
  application/usecases/post/dto/UpdatePostDto.ts
  domain/repositories/LikeRepository.ts
  domain/repositories/PostRepository.ts
  infra/repositories/supabase/SbPostRepository.ts
  next.config.ts
  store/queryTriggerStore.ts
Labels: ✨ Feature, 📬 API

#63 [DESIGN] 버튼 수정
  app/page.tsx
  app/posts/page.tsx
Labels: 🎨 UI

#64 [FIX] 모든 클릭 가능 요소에 cursor-pointer 속성 추가
  app/components/ComBoBox.tsx
  app/components/LikeButton.tsx
  app/components/PostHeader.tsx
  app/components/PostItem.tsx
  app/components/RegionSearchComboBox.tsx
  app/member/page.tsx
  app/onboarding/page.tsx
  app/onboarding/step1/page.tsx
  app/onboarding/step2/page.tsx
  app/onboarding/step3/page.tsx
  app/onboarding/step4/page.tsx
  app/posts/[post-id]/page.tsx
  app/weather/page.tsx
Labels: 🎨 UI
